version: '2'

services:
    mysql:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        links:
            - mysql
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/kalories
#            - ./logs/kalories:/var/www/kalories/app/logs
    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
